[package]
name = "retroboy_chip8"
version = "0.1.0"
edition = "2021"

[dependencies]
retroboy_common.workspace = true

anyhow.workspace = true
log.workspace = true
env_logger.workspace = true
rand = { workspace = true, features = ["getrandom"] }
getrandom = { workspace = true, features = ["js"] }
